benchmarks:
- benchmark_name: "gemm_multiple_run"
  trace_dir: "../microbenchmarks/gemm_multiple_run_bf16"
  csv_path: "../microbenchmarks/gemm_multiple_run_bf16"
  xlml_metrics_dir: "../microbenchmarks/gemm_multiple_run_bf16"
  xla_dump_dir: "../microbenchmarks/gemm_multiple_run_bf16/hlo_graphs"
  benchmark_sweep_params:
  - {m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: 'bfloat16'}
- benchmark_name: "gemm_multiple_run"
  trace_dir: "../microbenchmarks/gemm_multiple_run_fp8"
  csv_path: "../microbenchmarks/gemm_multiple_run_fp8"
  xlml_metrics_dir: "../microbenchmarks/gemm_multiple_run_fp8"
  xla_dump_dir: "../microbenchmarks/gemm_multiple_run_fp8/hlo_graphs"
  benchmark_sweep_params:
  - {m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: 'float8'}
- benchmark_name: "gemm_simple"
  trace_dir: "../microbenchmarks/gemm_simple"
  csv_path: "../microbenchmarks/gemm_simple"
  xlml_metrics_dir: "../microbenchmarks/gemm_simple"
  xla_dump_dir: "../microbenchmarks/gemm_simple/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 18432, n: 16384}
- benchmark_name: "gemm"
  trace_dir: "../microbenchmarks/gemm"
  csv_path: "../microbenchmarks/gemm"
  xlml_metrics_dir: "../microbenchmarks/gemm"
  xla_dump_dir: "../microbenchmarks/gemm/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 18432, n: 16384}
- benchmark_name: "gemm_accum"
  trace_dir: "../microbenchmarks/gemm_accum"
  csv_path: "../microbenchmarks/gemm_accum"
  xlml_metrics_dir: "../microbenchmarks/gemm_accum"
  xla_dump_dir: "../microbenchmarks/gemm_accum/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 16384, n: 18432}
- benchmark_name: "quantization"
  trace_dir: "../microbenchmarks/quantization"
  csv_path: "../microbenchmarks/quantization"
  xlml_metrics_dir: "../microbenchmarks/quantization"
  xla_dump_dir: "../microbenchmarks/quantization/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, n: 16384}
- benchmark_name: "transpose_quantization"
  trace_dir: "../microbenchmarks/transpose_quantization"
  csv_path: "../microbenchmarks/transpose_quantization"
  xlml_metrics_dir: "../microbenchmarks/transpose_quantization"
  xla_dump_dir: "../microbenchmarks/transpose_quantization/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, n: 16384}
- benchmark_name: "add"
  trace_dir: "../microbenchmarks/add"
  csv_path: "../microbenchmarks/add"
  xlml_metrics_dir: "../microbenchmarks/add"
  xla_dump_dir: "../microbenchmarks/add/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 4096, n: 16384}
- benchmark_name: "gemm_fp8_rowwise"
  trace_dir: "../microbenchmarks/gemm_fp8_rowwise"
  csv_path: "../microbenchmarks/gemm_fp8_rowwise"
  xlml_metrics_dir: "../microbenchmarks/gemm_fp8_rowwise"
  xla_dump_dir: "../microbenchmarks/gemm_fp8_rowwise/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 16384, n: 4096}