benchmarks:
- benchmark_name: "gemm"
  trace_dir: "../microbenchmarks/gemm"
  csv_path: "../microbenchmarks/gemm"
  xlml_metrics_dir: "../microbenchmarks/gemm"
  xla_dump_dir: "../microbenchmarks/gemm/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 1024, k: 7168, n: 3584}
  - {m: 8192, k: 21504, n: 7168}
  - {m: 2048, k: 16384, n: 768}
  - {m: 8192, k: 7168, n: 7168}
  - {m: 16384, k: 7168, n: 1024}
  - {m: 16384, k: 18432, n: 16384}
  - {m: 1024, k: 7168, n: 1152}
  - {m: 2048, k: 256, n: 16384}
  - {m: 16384, k: 4096, n: 16384}
  - {m: 1024, k: 14336, n: 7168}
  - {m: 4096, k: 1792, n: 7168}
  - {m: 16384, k: 1024, n: 8192}
  - {m: 4096, k: 8192, n: 4096}
  - {m: 2048, k: 9216, n: 16384}
  - {m: 1024, k: 7168, n: 10752}
  - {m: 4096, k: 7168, n: 2048}
  - {m: 64, k: 16384, n: 8192}
  - {m: 1024, k: 256, n: 7168}
  - {m: 4096, k: 10752, n: 7168}
  - {m: 1024, k: 7168, n: 2688}
  - {m: 2048, k: 7168, n: 21504}
  - {m: 16384, k: 16384, n: 256}
  - {m: 8192, k: 2048, n: 7168}
  - {m: 256, k: 512, n: 8192}
  - {m: 8192, k: 7168, n: 2048}
  - {m: 8192, k: 10752, n: 7168}
  - {m: 256, k: 4096, n: 16384}
  - {m: 2048, k: 16384, n: 18432}
  - {m: 16384, k: 16384, n: 1024}
  - {m: 16384, k: 10240, n: 8192}
  - {m: 2048, k: 1024, n: 16384}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 4096, k: 5376, n: 7168}
  - {m: 2048, k: 7168, n: 1024}
  - {m: 16384, k: 2048, n: 16384}
  - {m: 2048, k: 18432, n: 16384}
  - {m: 1024, k: 16384, n: 9216}
  - {m: 8192, k: 5376, n: 7168}
  - {m: 2048, k: 4096, n: 16384}
  - {m: 8192, k: 7168, n: 3584}
  - {m: 16384, k: 16384, n: 8192}
  - {m: 4096, k: 2688, n: 7168}
  - {m: 4096, k: 14336, n: 7168}
  - {m: 16384, k: 2048, n: 8192}
  - {m: 8192, k: 16384, n: 2048}
  - {m: 1024, k: 1024, n: 7168}
  - {m: 4096, k: 8192, n: 10240}
  - {m: 8192, k: 14336, n: 7168}
  - {m: 8192, k: 8192, n: 10240}
  - {m: 16384, k: 8192, n: 4096}
  - {m: 4096, k: 8192, n: 2048}
  - {m: 4096, k: 7168, n: 10752}
  - {m: 1024, k: 21504, n: 7168}
  - {m: 4096, k: 256, n: 7168}
  - {m: 1024, k: 7168, n: 7168}
  - {m: 8192, k: 7168, n: 10752}
  - {m: 2048, k: 2048, n: 16384}
  - {m: 4096, k: 8192, n: 5120}
  - {m: 8192, k: 8192, n: 5120}
  - {m: 1024, k: 7168, n: 14336}
  - {m: 32768, k: 2048, n: 7168}
  - {m: 32768, k: 7168, n: 2048}
  - {m: 1024, k: 10752, n: 7168}
  - {m: 32768, k: 7168, n: 512}
  - {m: 4096, k: 21504, n: 7168}
  - {m: 2048, k: 8192, n: 2560}
  - {m: 32768, k: 16384, n: 2048}
  - {m: 1024, k: 8192, n: 10240}
  - {m: 2048, k: 7168, n: 2048}
  - {m: 32768, k: 8192, n: 512}
  - {m: 512, k: 1024, n: 16384}
  - {m: 32768, k: 512, n: 7168}
  - {m: 16384, k: 1024, n: 7168}
  - {m: 2048, k: 256, n: 7168}
  - {m: 16384, k: 4096, n: 7168}
  - {m: 512, k: 4096, n: 8192}
  - {m: 8192, k: 7168, n: 256}
  - {m: 2048, k: 3584, n: 7168}
  - {m: 8192, k: 1024, n: 8192}
  - {m: 2048, k: 7168, n: 10752}
  - {m: 32768, k: 4096, n: 7168}
  - {m: 4096, k: 7168, n: 7168}
  - {m: 8192, k: 4096, n: 8192}
  - {m: 4096, k: 7168, n: 896}
  - {m: 512, k: 2048, n: 16384}
  - {m: 2048, k: 1024, n: 7168}
  - {m: 8192, k: 16384, n: 256}
  - {m: 16384, k: 7168, n: 2048}
  - {m: 1024, k: 16384, n: 768}
  - {m: 8192, k: 7168, n: 896}
  - {m: 8192, k: 10240, n: 8192}
  - {m: 2048, k: 21504, n: 7168}
  - {m: 4096, k: 8192, n: 1024}
  - {m: 2048, k: 7168, n: 7168}
  - {m: 256, k: 2048, n: 7168}
  - {m: 4096, k: 2048, n: 8192}
  - {m: 8192, k: 8192, n: 1024}
  - {m: 8192, k: 8192, n: 256}
  - {m: 8192, k: 2048, n: 8192}
  - {m: 4096, k: 5120, n: 8192}
  - {m: 8192, k: 2304, n: 16384}
  - {m: 1024, k: 512, n: 8192}
  - {m: 16384, k: 8192, n: 10240}
  - {m: 2048, k: 2048, n: 7168}
  - {m: 4096, k: 7168, n: 5376}
  - {m: 2048, k: 10752, n: 7168}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 8192, n: 2048}
  - {m: 1024, k: 7168, n: 256}
  - {m: 16384, k: 8192, n: 512}
  - {m: 4096, k: 16384, n: 2304}
  - {m: 8192, k: 7168, n: 5376}
  - {m: 1024, k: 4096, n: 16384}
  - {m: 64, k: 16384, n: 1024}
  - {m: 4096, k: 256, n: 16384}
  - {m: 2048, k: 5376, n: 7168}
  - {m: 2048, k: 7168, n: 3584}
  - {m: 16384, k: 8192, n: 5120}
  - {m: 256, k: 8192, n: 512}
  - {m: 4096, k: 16384, n: 4608}
  - {m: 4096, k: 256, n: 8192}
  - {m: 4096, k: 9216, n: 16384}
  - {m: 4096, k: 7168, n: 256}
  - {m: 2048, k: 14336, n: 7168}
  - {m: 64, k: 16384, n: 4096}
  - {m: 8192, k: 256, n: 8192}
  - {m: 8192, k: 16384, n: 4608}
  - {m: 8192, k: 9216, n: 16384}
  - {m: 1024, k: 10240, n: 8192}
  - {m: 8192, k: 7168, n: 21504}
  - {m: 4096, k: 1024, n: 16384}
  - {m: 1024, k: 8192, n: 1024}
  - {m: 8192, k: 16384, n: 18432}
  - {m: 1024, k: 8192, n: 256}
  - {m: 4096, k: 18432, n: 16384}
  - {m: 4096, k: 16384, n: 256}
  - {m: 4096, k: 4096, n: 16384}
  - {m: 1024, k: 2048, n: 8192}
  - {m: 256, k: 1024, n: 7168}
  - {m: 4096, k: 1024, n: 8192}
  - {m: 8192, k: 18432, n: 16384}
  - {m: 16384, k: 7168, n: 4096}
  - {m: 8192, k: 16384, n: 9216}
  - {m: 4096, k: 8192, n: 256}
  - {m: 4096, k: 16384, n: 1024}
  - {m: 1024, k: 7168, n: 5376}
  - {m: 4096, k: 10240, n: 8192}
  - {m: 8192, k: 16384, n: 1024}
  - {m: 8192, k: 4608, n: 16384}
  - {m: 4096, k: 2048, n: 16384}
  - {m: 2048, k: 8192, n: 5120}
  - {m: 2048, k: 2048, n: 8192}
  - {m: 8192, k: 8192, n: 2560}
  - {m: 1024, k: 512, n: 16384}
  - {m: 1024, k: 16384, n: 4608}
  - {m: 2048, k: 5120, n: 8192}
  - {m: 4096, k: 7168, n: 14336}
  - {m: 1024, k: 7168, n: 21504}
  - {m: 32768, k: 512, n: 8192}
  - {m: 8192, k: 7168, n: 14336}
  - {m: 2048, k: 16384, n: 2304}
  - {m: 32768, k: 1024, n: 16384}
  - {m: 32768, k: 4096, n: 16384}
  - {m: 4096, k: 7168, n: 21504}
  - {m: 4096, k: 16384, n: 18432}
  - {m: 2048, k: 16384, n: 4608}
  - {m: 512, k: 7168, n: 384}
  - {m: 2048, k: 256, n: 8192}
  - {m: 32768, k: 7168, n: 4096}
  - {m: 2048, k: 7168, n: 256}
  - {m: 32768, k: 16384, n: 1024}
  - {m: 512, k: 384, n: 7168}
  - {m: 4096, k: 16384, n: 9216}
  - {m: 16384, k: 5120, n: 8192}
  - {m: 32768, k: 16384, n: 4096}
  - {m: 16384, k: 8192, n: 8192}
  - {m: 2048, k: 1024, n: 8192}
  - {m: 32768, k: 16384, n: 8192}
  - {m: 8192, k: 256, n: 7168}
  - {m: 2048, k: 4096, n: 8192}
  - {m: 16384, k: 16384, n: 2304}
  - {m: 32768, k: 8192, n: 16384}
  - {m: 4096, k: 3584, n: 7168}
  - {m: 2048, k: 8192, n: 256}
  - {m: 2048, k: 8192, n: 1024}
  - {m: 4096, k: 896, n: 7168}
  - {m: 256, k: 2048, n: 8192}
  - {m: 512, k: 4096, n: 7168}
  - {m: 8192, k: 3584, n: 7168}
  - {m: 4096, k: 7168, n: 4096}
  - {m: 1024, k: 2048, n: 7168}
  - {m: 2048, k: 10240, n: 8192}
  - {m: 16384, k: 256, n: 8192}
  - {m: 16384, k: 16384, n: 4608}
  - {m: 16384, k: 9216, n: 16384}
  - {m: 8192, k: 1024, n: 7168}
  - {m: 64, k: 16384, n: 2048}
  - {m: 16384, k: 768, n: 16384}
  - {m: 16384, k: 16384, n: 18432}
  - {m: 1024, k: 5376, n: 7168}