benchmarks:
- benchmark_name: "gemm_accum"
  trace_dir: "../microbenchmarks/gemm_accum"
  csv_path: "../microbenchmarks/gemm_accum"
  xlml_metrics_dir: "../microbenchmarks/gemm_accum"
  xla_dump_dir: "../microbenchmarks/gemm_accum/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 2048, n: 18432}
  - {m: 16384, k: 8192, n: 4608}
  - {m: 16384, k: 1024, n: 16384}
  - {m: 8192, k: 16384, n: 768}
  - {m: 8192, k: 2048, n: 768}
  - {m: 512, k: 16384, n: 7168}
  - {m: 16384, k: 4096, n: 16384}
  - {m: 8192, k: 4096, n: 10240}
  - {m: 16384, k: 4096, n: 4096}
  - {m: 16384, k: 32768, n: 8192}
  - {m: 7168, k: 2048, n: 5376}
  - {m: 16384, k: 8192, n: 18432}
  - {m: 16384, k: 16384, n: 9216}
  - {m: 16384, k: 4096, n: 8192}
  - {m: 16384, k: 2048, n: 9216}
  - {m: 8192, k: 8192, n: 768}
  - {m: 8192, k: 4096, n: 2048}
  - {m: 64, k: 2048, n: 8192}
  - {m: 7168, k: 8192, n: 5376}
  - {m: 224, k: 1024, n: 7168}
  - {m: 16384, k: 8192, n: 9216}
  - {m: 224, k: 4096, n: 7168}
  - {m: 8192, k: 4096, n: 5120}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 8192, k: 16384, n: 10240}
  - {m: 16384, k: 16384, n: 4096}
  - {m: 8192, k: 2048, n: 10240}
  - {m: 16384, k: 2048, n: 4096}
  - {m: 8192, k: 16384, n: 2048}
  - {m: 7168, k: 512, n: 14336}
  - {m: 8192, k: 2048, n: 2048}
  - {m: 16384, k: 8192, n: 16384}
  - {m: 8192, k: 8192, n: 10240}
  - {m: 8192, k: 16384, n: 5120}
  - {m: 8192, k: 8192, n: 2048}
  - {m: 7168, k: 512, n: 21504}
  - {m: 7168, k: 256, n: 1024}
  - {m: 7168, k: 4096, n: 14336}
  - {m: 7168, k: 1024, n: 5376}
  - {m: 7168, k: 512, n: 256}
  - {m: 7168, k: 2048, n: 512}
  - {m: 7168, k: 4096, n: 21504}
  - {m: 7168, k: 512, n: 4096}
  - {m: 7168, k: 32768, n: 1024}
  - {m: 7168, k: 2048, n: 14336}
  - {m: 7168, k: 8192, n: 512}
  - {m: 7168, k: 1024, n: 10752}
  - {m: 16384, k: 32768, n: 4096}
  - {m: 7168, k: 8192, n: 14336}
  - {m: 8192, k: 32768, n: 2048}
  - {m: 512, k: 512, n: 8192}
  - {m: 7168, k: 4096, n: 4096}
  - {m: 7168, k: 2048, n: 21504}
  - {m: 7168, k: 8192, n: 21504}
  - {m: 16384, k: 2048, n: 768}
  - {m: 7168, k: 16384, n: 4096}
  - {m: 7168, k: 2048, n: 4096}
  - {m: 8192, k: 1024, n: 8192}
  - {m: 16384, k: 1024, n: 2048}
  - {m: 16384, k: 8192, n: 768}
  - {m: 8192, k: 4096, n: 8192}
  - {m: 16384, k: 4096, n: 1280}
  - {m: 7168, k: 4096, n: 512}
  - {m: 7168, k: 8192, n: 4096}
  - {m: 8192, k: 16384, n: 8192}
  - {m: 16384, k: 16384, n: 2048}
  - {m: 7168, k: 2048, n: 7168}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 8192, n: 2048}
  - {m: 8192, k: 256, n: 1024}
  - {m: 16384, k: 1024, n: 768}
  - {m: 7168, k: 2048, n: 2048}
  - {m: 7168, k: 32768, n: 4096}
  - {m: 16384, k: 256, n: 2048}
  - {m: 7168, k: 8192, n: 2048}
  - {m: 8192, k: 512, n: 4096}
  - {m: 7168, k: 512, n: 7168}
  - {m: 512, k: 32768, n: 8192}
  - {m: 16384, k: 16384, n: 768}
  - {m: 8192, k: 4096, n: 4096}
  - {m: 16384, k: 32768, n: 2048}
  - {m: 7168, k: 512, n: 2048}
  - {m: 1024, k: 256, n: 16384}
  - {m: 128, k: 2048, n: 16384}
  - {m: 7168, k: 4096, n: 2048}
  - {m: 128, k: 8192, n: 16384}
  - {m: 7168, k: 1024, n: 896}
  - {m: 1024, k: 32768, n: 16384}
  - {m: 512, k: 128, n: 7168}
  - {m: 224, k: 2048, n: 7168}
  - {m: 128, k: 4096, n: 16384}
  - {m: 8192, k: 1024, n: 768}
  - {m: 16384, k: 4096, n: 18432}
  - {m: 224, k: 8192, n: 7168}
  - {m: 8192, k: 4096, n: 768}
  - {m: 16384, k: 512, n: 4096}
  - {m: 128, k: 16384, n: 16384}
  - {m: 16384, k: 512, n: 8192}
  - {m: 8192, k: 512, n: 2048}
  - {m: 16384, k: 16384, n: 18432}