benchmarks:
- benchmark_name: "quantization_static_scaling"
  trace_dir: "../microbenchmarks/quantization_static_scaling"
  csv_path: "../microbenchmarks/quantization_static_scaling"
  xlml_metrics_dir: "../microbenchmarks/quantization_static_scaling"
  xla_dump_dir: "../microbenchmarks/quantization_static_scaling/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 512, n: 4096}
  - {m: 4096, n: 1024}
  - {m: 512, n: 16384}
  - {m: 8192, n: 1024}
  - {m: 16384, n: 1024}
  - {m: 256, n: 7168}
  - {m: 512, n: 896}
  - {m: 8192, n: 16384}
  - {m: 16384, n: 16384}
  - {m: 8192, n: 7168}