benchmarks:
- benchmark_name: "rmsnorm_bwd"
  trace_dir: "../microbenchmarks/rmsnorm_bwd"
  csv_path: "../microbenchmarks/rmsnorm_bwd"
  xlml_metrics_dir: "../microbenchmarks/rmsnorm_bwd"
  xla_dump_dir: "../microbenchmarks/rmsnorm_bwd/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 2048, n: 7168}
  - {m: 4096, n: 8192}
  - {m: 128, n: 7168}
  - {m: 2048, n: 8192}
  - {m: 512, n: 7168}
  - {m: 256, n: 16384}
  - {m: 1024, n: 16384}
  - {m: 4096, n: 16384}
  - {m: 256, n: 8192}
  - {m: 2048, n: 16384}