benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 8192, multiplier: 2}, dtype: "float32",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "1x4x1" , op_dimension: 1, num_runs: 5} # Parallel Replica
  - {matrix_dim_range: {start: 2, end: 8192, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4x8", ici_size_range: 128, sharding_strategy: "1x1x4", op_dimension: 1, num_runs: 5} # Non Parallel Replica
  trace_dir: "../microbenchmarks/all_reduce_1d"
  csv_path: "../microbenchmarks/all_reduce_1d"
  xlml_metrics_dir: "../microbenchmarks/all_reduce_1d"
  xla_dump_dir: "../microbenchmarks/all_reduce_1d/hlo_graphs"