benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 32768, multiplier: 2}, dtype: "float32",  mesh_shape: "1x1x32", ici_size_range: 32, sharding_strategy: "1x1x32" , op_dimension: 1, num_runs: 5}
  trace_dir: "../microbenchmarks/all_reduce_2d"
  csv_path: "../microbenchmarks/all_reduce_2d"
  xlml_metrics_dir: "../microbenchmarks/all_reduce_2d"
  xla_dump_dir: "../microbenchmarks/all_reduce_2d/hlo_graphs"
