benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 32768, multiplier: 2}, dtype: "float32",  mesh_shape: "4x32x2", ici_size_range: 256, sharding_strategy: "4x32x1", op_dimension: 3, num_runs: 5} # Parallel Replica Groups
  - {matrix_dim_range: {start: 2, end: 32768, multiplier: 2}, dtype: "float32",  mesh_shape: "4x8x8", ici_size_range: 256, sharding_strategy: "4x8x8", op_dimension: 3, num_runs: 5} # Non Parallel Replica Groups
  trace_dir: "../microbenchmarks/all_to_all_3d_256"
  csv_path: "../microbenchmarks/all_to_all_3d_256"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_3d_256"
  xla_dump_dir: "../microbenchmarks/all_to_all_3d_256/hlo_graphs"