benchmarks:
- benchmark_name: "single_device_hbm_copy"
  benchmark_sweep_params:
  - {num_elements_range: {start: 1048576, end: 8589934592, multiplier: 2}, dtype: "bfloat16", num_runs: 1}
  trace_dir: "../microbenchmarks/hbm"
  csv_path: "../microbenchmarks/hbm"
  xlml_metrics_dir: "../microbenchmarks/hbm"
  xla_dump_dir: "../microbenchmarks/hbm/hlo_graphs"